# Generated by Django 3.2.2 on 2021-05-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20210526_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='post',
            new_name='notice',
        ),
    ]
