# Generated by Django 3.2.2 on 2021-05-29 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_reply_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='notice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='notices.notice'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(default='Готов помочь!'),
        ),
    ]
