# Generated by Django 3.2.2 on 2021-05-29 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_auto_20210529_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='notice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='notices.notice'),
        ),
    ]
